# Generated by Django 3.2.9 on 2022-01-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20220124_1751"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postsvotes",
            old_name="id_voted",
            new_name="is_voted",
        ),
    ]
