# Generated by Django 3.2.9 on 2022-01-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_rename_id_voted_postsvotes_is_voted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postsvotes",
            name="is_voted",
            field=models.BooleanField(default=True),
        ),
    ]
