version: '3.8'

services:
  web:
    image: gamdckr/news-api:v1.0
    command: >
      sh -c "python3 manage.py flush --no-input &&
             python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000 &&
             python3 manage.py crontab add"
    ports:
      - 8000:8000
    env_file:
      - ../.env.dev
    depends_on: 
      - db
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env.db

volumes:
  postgres_data:
